//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiramsCraftLocalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiramsCraftProduct
    {
        public HiramsCraftProduct()
        {
            this.MaterialProviders = new HashSet<MaterialProvider>();
            this.ServiceProviders = new HashSet<ServiceProvider>();
        }
    
        public int ProductId { get; set; }
        public byte[] ProductImage { get; set; }
        public string ImageFileName { get; set; }
        public string ImageMIMEType { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public double ProductCost { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public string Units { get; set; }
        public int ProductType { get; set; }
        public int WoodType { get; set; }
        public int WoodStainType { get; set; }
        public int MetalType { get; set; }
        public int MetalFinish { get; set; }
    
        public virtual ICollection<MaterialProvider> MaterialProviders { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
    }
}
