//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiramsCraftLocalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiramsCraftPO
    {
        public int PurchaseOrderId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string OrderJSON { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> ItemsCount { get; set; }
        public int OrderStatus { get; set; }
        public double OrderTotal { get; set; }
        public string CustFirstname { get; set; }
        public string CustLastname { get; set; }
        public string Email { get; set; }
        public string CreditCardType { get; set; }
        public int CardNumber { get; set; }
        public string CardExpiration { get; set; }
        public string ShipFullname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipInstructions { get; set; }
    }
}
