//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiramsCraftLocalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public int ServiceProviderId { get; set; }
        public string Service { get; set; }
        public string Description { get; set; }
        public decimal EstimatedCost { get; set; }
        public decimal ActualCost { get; set; }
        public System.DateTime LeadTime { get; set; }
        public bool HasMinimumOrder { get; set; }
        public string MinimumOrder { get; set; }
        public bool HasBulkDiscount { get; set; }
        public string BulkDiscount { get; set; }
        public int ProviderId { get; set; }
        public int ProductId { get; set; }
    
        public virtual HiramsCraftProduct HiramsCraftProduct { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
